spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5


#  datasource:
#    url: jdbc:mysql://49.234.12.16:3306/user?serverTimezone=GMT%2B8
#    username: root
#    password: zk123n456

#mybatis:
#  mapper-locations: classpath*:mapper/*.xml     # mapper映射文件


