kind: pipeline
name: default
steps:
  - name: build
    image: maven:3-jdk-10
    commands:
      - pwd
      - cd ./zel
      - mvn clean package
    volumes:
      - name: cache
        path: /home/ubuntu/docker/maven/m2
  - name: run
    image: java:openjdk-8
    commands:
      - pwd
      - cd ./zel
      - cp zel-web/target/web-0.0.1-SNAPSHOT.jar .
      - sh run.sh
