kind: pipeline
name: default
type:
steps:
  - name: run
    commands:
      - sh build.sh

  # 代码编译
#  - name: build
#    image: maven:3-jdk-10
#    commands:
#      - pwd
#      - mvn clean package
#    volumes:
#      - name: cache
#        path: /home/ubuntu/docker/maven/m2
#  - name: run
#    image: java:openjdk-8
#    commands:
#      - pwd
#      - cp zel-web/target/web-0.0.1-SNAPSHOT.jar .
#      - nohup java -jar web-0.0.1-SNAPSHOT.jar --server.port=9527 &
      #- sh run.sh
