server:
  port: 8001

spring:
  application:
    name: gateway

  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 49.234.12.16:8848

    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        # 配置 sentinel 控制台的地址
        dashboard: 49.234.12.16:8080

#    gateway:
#      routes:
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**


feign:
  sentinel:
    # 开启 sentinel 对 Feign 的支持
    enabled: true



